{
 "title": "REMLA22 Group3",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "General Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate of Change for Total Number of Suggestions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(nr_suggestions{}[$__rate_interval])",
     "legendFormat": "Web App Instance"
    }
   ]
  },
  {
   "title": "Rate of Change for Total Number of Submissions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(nr_submissions{}[$__rate_interval])",
     "legendFormat": "Web App Instance"
    }
   ]
  },
  {
   "title": "Release/Shadow Deployment Comparison",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Share of Selected Tags from Predictions",
   "type": "timeseries",
   "description": "Higher is better.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "release_agg_share_chosen_tags{}/nr_submissions{}",
     "legendFormat": "Release Model Instance"
    },
    {
     "expr": "shadow_agg_share_chosen_tags{}/nr_submissions{}",
     "legendFormat": "Shadow Model Instance"
    }
   ]
  },
  {
   "title": "Share of Manually Added Tags",
   "type": "timeseries",
   "description": "Lower is better.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "release_agg_share_manual_tags{}/nr_submissions{}",
     "legendFormat": "Release Model Instance"
    },
    {
     "expr": "shadow_agg_share_manual_tags{}/nr_submissions{}",
     "legendFormat": "Shadow Model Instance"
    }
   ]
  },
  {
   "title": "Share of Newly Added Tags",
   "type": "timeseries",
   "description": "Lower is better.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "release_agg_share_new_tags{}/nr_submissions{}",
     "legendFormat": "Release Model Instance"
    },
    {
     "expr": "shadow_agg_share_new_tags{}/nr_submissions{}",
     "legendFormat": "Shadow Model Instance"
    }
   ]
  }
 ]
}